### PR TITLE
Make MonologFormatter normalize method compatible with parent.

### PR DESCRIPTION
**Pull request by mrelevance**
Fix normalize method not being compatible with Monolog's normalize method.

### CODE REVIEW

**Comment by dmitry-ivanov** [comment]
@mrelevance Thanks for your contribution!

But there are failing tests for PHP 7.0 on that PR:
https://travis-ci.org/github/dmitry-ivanov/laravel-console-logger/jobs/671692681

> Error: Call to undefined function Illuminated\Console\Loggable\FileChannel\is_iterable()

This function is available [only from PHP 7.1+](https://www.php.net/manual/en/function.is-iterable.php).

**Comment by mrelevance** [comment]
@dmitry-ivanov Sorry about that. Everything has been fixed.

**Comment by dmitry-ivanov** [comment]
Thank you 👍 

I'll do a release in a few minutes.

**Comment by dmitry-ivanov** [comment]
@mrelevance [5.5.4 released](https://github.com/dmitry-ivanov/laravel-console-logger/releases/tag/5.5.4) 👍

**Pull request merged**
